FROM mq/chatbot_controller_op
FROM nvidia/cuda:12.0.1-base-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive
# ARG DEBIAN_FRONTEND=noninteractive
# ARG GRADIO_SERVER_PORT=8888
# ENV GRADIO_SERVER_PORT=${GRADIO_SERVER_PORT}
# ENV TZ Asia/Vietnam

WORKDIR /MqgptApp

ADD ./src /MqgptApp

ADD ./bashes/run_app.sh /MqgptApp
RUN ls -la
