# first stage
FROM nvidia/cuda:12.0.1-base-ubuntu20.04
FROM python:3.9 AS builder

ARG DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
#         # git \
        python3-pip \
        python3-dev \
#         python3-opencv \
        # libglib2.0-0 \
        # libgl1-mesa-glx 

WORKDIR /app
COPY pyproject.toml /app/pyproject.toml
RUN python3 -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"
# RUN . /app/venv/bin/activate
RUN pip3 install pycocotools
# RUN pip install --upgrade pip
RUN pip3 install -e .
RUN pip3 install PyPDF2

# second unnamed stage
FROM python:3.9-slim AS runner
WORKDIR /MqgptController
COPY --from=builder /app/venv /MqgptController/venv
RUN apt-get update && apt-get install -y libglib2.0-0 libgl1-mesa-glx

ENV PATH="/MqgptController/venv/bin:$PATH"
# ADD pyproject.toml /MqgptController/pyproject.toml
# Install python dependencies
# RUN python3 -m pip install -e .
# RUN pip --no-cache-dir install -r requirements.txt
ADD ./src /MqgptController/
ADD ./bashes/run_controller.sh /MqgptController/

RUN ls -la

CMD ["python3", "controller.py"]

# docker build -t mq/chatbot_controller_op --load --rm -f Dockerfile_controller .
# docker run -d -p 21001:21001 --name mqbot mq/chatbot_controller_op

# docker run -p 21001:21001 --name mqbot -it mq/chatbot_controller_op sh /MqgptController/run_controller.sh

