version: "3.8"

services:
  fluentbit:
    container_name: fluentbit
    build: 
      context: fluentbit/
      dockerfile: ./fluentbit/Dockerfile_fluentbit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      almighty_bot_mynetwork:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # network_mode: "host"
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/config/fluent-bit.conf
    profiles:
      - fluentbit

  elasticsearch:
    container_name: elasticsearch
    build: 
      context: elasticsearch/
      dockerfile: ./Dockerfile_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      xpack.security.enabled: true
      ELASTIC_PASSWORD: "els123"
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      almighty_bot_mynetwork:
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # network_mode: "host"
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - ./elasticsearch/data:/usr/share/elasticsearch/data:z
    profiles:
      - elasticsearch

networks:
  almighty_bot_mynetwork:
    name: almighty_bot_mynetwork
    driver: bridge
    external: true

# docker compose -f fluent-bit.yml --profile fluentbit up -d