FROM python:3.11-slim

RUN apt-get update 

RUN apt-get install -y \
        ffmpeg \
        nano \
        curl

RUN pip install --upgrade pip

WORKDIR /app_knowledge
COPY ./requirements/requirement_app_knowledge.txt /app_knowledge/requirements.txt
RUN python3 -m pip --no-cache-dir install --ignore-installed -r /app_knowledge/requirements.txt

COPY ./src/base /app_knowledge/base
COPY ./src/app_knowledge.py /app_knowledge/app_knowledge.py

# CMD ["python3", "app_knowledge.py"]

# docker build -t mq/knowledge_bot --load --rm -f Dockerfile_knowledge_bot .
# docker run -d -p 8887:8887 --gpus all --name knowledge_bot mq/knowledge_bot
# docker run -d -p 8887:8887 -v ./weights:/app/weights -v ./logs:/app/logs --name knowledge_bot mq/knowledge_bot