FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Ho_Chi_Minh

RUN apt-get update && \
        apt install software-properties-common -y && \
        add-apt-repository ppa:deadsnakes/ppa -y && \
        apt-get install -y python3.11 python3.11-distutils

RUN apt-get install -y \
        python3-pip \
        python3.11-dev \
        ffmpeg \
        nano \
        curl

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
RUN python3.11 -m pip install --upgrade pip

WORKDIR /controller
COPY ./requirements/requirement_controller.txt /controller/requirements.txt
RUN python3.11 -m pip --no-cache-dir install --ignore-installed -r /controller/requirements.txt

COPY ./src/base /controller/base
COPY ./src/controller.py /controller/controller.py

# CMD ["python3.11", "controller.py"]

# docker build -t mq/controller_bot --load --rm -f Dockerfile_controller_bot .
# docker run -d -p 8888:8888 --gpus all --name controller_bot mq/controller_bot
# docker run -d -p 8888:8888 --name controller_bot mq/controller_bot