FROM python:3.11-slim

RUN apt-get update 

RUN apt-get install -y \
        ffmpeg \
        nano \
        curl

RUN pip install --upgrade pip

WORKDIR /controller
COPY ./requirements/requirement_controller.txt /controller/requirements.txt
RUN python3 -m pip --no-cache-dir install --ignore-installed -r /controller/requirements.txt

COPY ./src/base /controller/base
COPY ./src/controller.py /controller/controller.py

EXPOSE 21001

# ENTROPY ["/bin/bash"]
# CMD ["python3.11", "controller.py"]

# docker build -t mq/controller_bot --load --rm -f Dockerfile_controller .
# docker run -d -p 21001:21001 --gpus all --name controller_bot mq/controller_bot
# docker run -d -p 21001:21001 --name controller_bot mq/controller_bot