FROM python:3.11-slim

RUN apt-get update 

RUN apt-get install -y \
        ffmpeg \
        nano \
        curl

RUN pip install --upgrade pip

WORKDIR /retrievalwk
COPY ./requirements/requirement_retrievalwk.txt /retrievalwk/requirements.txt
RUN python3 -m pip --no-cache-dir install --ignore-installed -r /retrievalwk/requirements.txt

COPY ./src/base /retrievalwk/base
COPY ./src/llava_module/retrieval_worker2.py /retrievalwk/retrievalwk.py

# CMD ["python3.11", "retrievalwk.py"]

# docker build -t mq/retrievalwk_bot --load --rm -f Dockerfile_retrievalwk_bot .
# docker run -d -p 21002:21002 --gpus all --name retrievalwk_bot mq/retrievalwk_bot
# docker run -d -p 21002:21002 --name retrievalwk_bot mq/retrievalwk_bot