FROM python:3.11-slim

RUN apt-get update 

RUN apt-get install -y \
        ffmpeg \
        nano \
        curl

RUN pip install --upgrade pip

WORKDIR /app
COPY ./requirements/requirement_app.txt /app/requirements.txt
RUN python3 -m pip --no-cache-dir install --ignore-installed -r /app/requirements.txt

COPY ./icons /app/icons
COPY cert.pem /app/cert.pem
COPY key.pem /app/key.pem
COPY ./src /app/

# CMD ["python3.11", "app2.py"]

# docker build -t mq/app_bot --load --rm -f Dockerfile_app .
# docker run -d -p 8888:8888 --gpus all --name app_bot mq/app_bot
# docker run -d -p 8888:8888 -v ./weights:/app/weights -v ./logs:/app/logs --name app_bot mq/app_bot