ARG ELASTIC_VERSION=8.15.0

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}

# ENV ELASTIC_PASSWORD=els123
EXPOSE 9200
# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
